### PR TITLE
Improve nuget lookup

### PR DESCRIPTION
**Pull request by bitcrazed**
Made several improvements to nuget-build.cmd to work better on (non-Appveyor) command-lines:

* Specifically look for NuGet on the path
* Display an error if NuGet not found on the path or in AppVeyor-specific location
* Replaced all the @ prefixes with file-wide '@echo off'
* Add output info on location of NuGet and Package name and build #

Hope this works for you? Happy to make further changes if you'd like?

### CODE REVIEW

**Comment by ebekker** [comment]
Can you clarify what this line is about:
`IF NOT EXIST "nuget-build.cmd" SET FOO=BAR`

**Comment by bitcrazed** [comment]
Me being an idiot. Will fix in the AM. Thanks.

**Comment by bitcrazed** [comment]
Removed the offending line. Apologies for that!

**Comment by ebekker** [comment]
Thanks!

**Pull request merged**
