### PR TITLE
#52 Add ability to specify file path for Manual provider

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
This is a little hacky, but this part of the code already seems a little hacky to start with ;-)

Works well though, and I can now specify a path and do a complete end-to-end request for certificate without touching the keyboard!

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Alright, that first commit was REALLY hacky, so I cleaned it up. I would also consider building the other JSON files in the way I'm doing it here, that way you're more flexible in adding more of them when necessary and it would help with that TODO you have there to clean up the provider resolution mechanism.

**Comment by ebekker** [comment]
This is a bit better in that it at least gives you an automated option for the manual path, but it still doesn't feel like the right solution.  I think I have a better idea that I'm working on for general-purpose extensibility  and a better provider model.  I'll commit that soon and would love to get some feedback on it.

**Comment by ebekker** [comment]
Thanks!

**Comment by nul800sebastiaan** [comment]
Interesting, looking forward to it.

Thanks for merging them in!

**Pull request merged**
